services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: storyfolio
      POSTGRES_USER: story
      POSTGRES_PASSWORD: storypass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
