server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/storyfolio
    username: story
    password: storypass
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user,user:email

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger


management:
  endpoints:
    web:
      exposure:
        include: health,info
