server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/storyfolio
    username: story
    password: storypass
  jpa:
    hibernate:
      ddl-auto: validate   # схему создаём миграциями Flyway, а не руками Hibernate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration

# OAuth2 вход через GitHub (значения позже подставишь из GitHub Developer Settings)
github:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID:changeme}
            client-secret: ${GITHUB_CLIENT_SECRET:changeme}
            scope: read:user, user:email
        provider:
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

management:
  endpoints:
    web:
      exposure:
        include: health,info
